# Jekyll
safe:      true
exclude:   ["README.md"]
permalink: /:year/:month/:title/
timezone:  Europe/London

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Sass
sass:
    sass_dir: /assets/css/_sass/
    style:    compressed

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            "Luke Armstrong"
email:            "me@lukearmstrong.co.uk"
description:      "Web Developer"
url:              "https://lukearmstrong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "6c61"
github_username:  "lukearmstrong"

# Collections
collections:
  games:
    output: true
    permalink: /games/:title/

# Default Page Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"